# Maximum number of threads used in a submitted job
max_threads: 20

steps:
  # Perform genome download and indexation steps
  # Automatically turned `true` if mapping is performed
  # Automatically turned `true` if download_fastq_screen_indexes is `true`
  install: false

  # Download (true) or not (false) pre-built fastq screen indexes
  # Set to `false` if you want to use your own indexes
  # Set to `true` if you want this pipeline to download and store fastq screen indexes
  download_fastq_screen_indexes: false

  # Perform fastq trimming and quality checks
  # Automatically turned `true` if mapping is performed
  trimming: true

  # Perform fastq trimming + mapping.
  # Missing genome sequences/annotation/indexes will run installation process
  # Automatically tuned `true` if peak-calling is performed
  # Automatically tuned `true` if coverage analysis is performed
  # Automatically tuned `true` if differential coverage analysis is performed
  # Automatically tuned `true` if motives analysis is performed
  mapping: true

  # Perform fastq trimming + mapping + coverage
  # Missing genome sequences/annotation/indexes will run installation process
  # Automatically tuned `true` if differential coverage analysis is performed
  coverage: true

  # Perform fastq trimming + mapping + peak-calling
  # Missing genome sequences/annotation/indexes will run installation process
  # Automatically tuned `true` if differential coverage analysis is performed
  # Automatically tuned `true` if motives analysis is performed
  calling: true

  # Perform fastq trimming + mapping + peak-calling + differential coverage analysis
  # Missing genome sequences/annotation/indexes will run installation process
  diff_cov: false

  # Perform fastq trimming + mapping + peak-calling + motives analysis
  # Missing genome sequences/annotation/indexes will run installation process
  motives: true


# Must be one of the following
# Main differences:
# * `chip-seq`:
#    - Base pipeline
#
# * `atac-seq`: 
#    - Read shifting is performed on aligned reads (on BAM files, after deduplication)
#
# * `cut&run` :
#    - No deduplication
#    - Seacr is used as a peak caller alongside with Macs2
#
# * `cut&tag` :
#    - No deduplication
#
# * `medip-seq`:
#    - CpG density calculation for peak-coverage normalization/merging/QC
#
# * `og-seq`:
#   - Specific bias accounted in CSAW
#
# * `gro-seq`:
#   - Specific bias accounted in CSAW
#
# * `ribo-seq`:
#   - Specific bias accounted in coverage analysis
#
# * `mnase-seq`:
#   - Specific bias accounted in coverage analysis
#
protocol: 'cutnrun'

# Path to the design file. It must be a TSV-formatted text file
# with the following columns (case matters, order does not matter):
# - Sample_id       (Required)  Must be unique
# - Upstream_file   (Required)
# - Downstream_file (Optional)  Optional for single-ended libraries
# - Fragment_size   (Optional)  Required if and only if sample is single-ended
# - Input           (Optional)  Optional Sample_id of the corresponding input file. 
#                               Leave empty if this file is an Input.
# - Protocol        (Optional)  See `protocol` above
# - Organism        (Optional)  Ensembl organism name. eg. `homo_sapiens`
# - Build           (Optional)  Ensembl organism build. eg: `GRCh38`
# - Release         (Optional)  Ensembl organism release. eg: `109`
design: config/design.tsv

reference:
  # Data are from xenograft.
  pdx: true

  # Ensembl organism name. eg. `homo_sapiens`.
  species: homo_sapiens

  # Ensembl organism build. eg: `GRCh38`.
  build: GRCh38

  # Ensembl organism release. eg: `109`.
  release: "109"

  # Path to genome sequence file (FASTA formatted, NOT gzipped)
  # A missing sequence file will be downloaded and indexed.
  # genome_fasta: /path/to/sequences.fasta

  # Path to genome annotation file (GTF formatted, NOT gzipped)
  # A missing annotation file will be downloaded.
  # genome_gtf: /path/to/annotation.gtf

  # Path to bowtie2_index directory.
  # A missing bowtie2 index directory will lead to genome indexation.
  # bowtie2_index: /path/to/bowtie2_index/dir/

  # Path to blacklisted intervals.
  # A missing interval file will be downloaded.
  # blacklist: /path/to/blacklist.bed

  # Path to directory containing fastq_screen configuration file
  fastq_screen_config: config/fastq_screen.conf

  # Path to genome sequence in TwoBit format
  # A missing genome sequence in TwoBit format will lead
  # to a fasta to TwoBit conversion
  # two_bits: /path/to/sequence.2bit

  # Path to mouse sequence genome in case of PDX
  # A missinge genome sequence will be downloaded.
  # WARNING: If you're working with mouse-only datasets,
  #          Do not use this variable. Use `genome_fasta`.
  # mouse_fasta: /path/to/sequences.fasta

  # Path to a bed-file containing regions of interest (roi).
  # The whole pipeline would stick to these regions only.
  # WARNING: The rest of the genome will be ignored if this
  #          option is enabled.
  # roi_bed: /path/to/intervals.bed

  # Path to Xenome indexed genomes
  # A missing index directory will be re-computed.
  # xenome_index: 
  #  - /path/to/index/files


# Macs2 peak caller parameters
macs2:
  # Perform broad peak calling using Macs2
  broad: true

  # Perform narrow peak calling using Macs2
  narrow: true


# Seacr peak caller for Cut&Run parameters
seacr:
  # Perform stringent peak calling using Seacr
  stringent: true

  # Perform relaxed peak calling using Seacr
  relaxed: true

# Options to define differential peak coverage
differential_peak_coverage:
  # One item per comparison. For multiple comparisons, add a new item for each single comparison.
  - model_name: Condition  # Human readable unique comparison name
    reference: WT  # Reference samples. WARNING: reference ≠ input. Reference = fold-change denominator.
    tested: Mut  # Tested samples, the fold-change numerator.
    formula: "~Condition"

# The following options involve trimming (fastp)
# trimming:
  # Contaminent, vector, adapter. Comment to ignore.
  # adapters: --adapter_sequence GATCGGAAGAGCACACGTCTGAACTCCAGTCA

  # Fastp trimming options. Comment to ignore.
  # fastp_extra: none


# The following options involve mapping and post-mapping corrections
# mapping:
#   deeptools:
#     alignment_sieve_extra: --shift -200 -200


# The following options involve motifs over signal
finger_prints:
  motifs:
    - CTCF